import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { indexRepository } from "../src/indexer/typescript-indexer.js";
import type { CodeSymbol } from "../src/indexer/types.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "fixtures", "typescript-repo");
const COMMIT = "a".repeat(40);

function index(): CodeSymbol[] {
  return indexRepository({ repositoryRoot: repoRoot, repositoryCommit: COMMIT }).symbols;
}

function byQualifiedName(symbols: CodeSymbol[], qualifiedName: string, kind?: CodeSymbol["kind"]): CodeSymbol[] {
  return symbols.filter((s) => s.qualifiedName === qualifiedName && (kind === undefined || s.kind === kind));
}

describe("indexRepository — exclusions (REQ-CORE-011; prelim spec §8.4)", () => {
  // Built at runtime rather than checked into tests/fixtures/: a fixture that
  // needs a real, functioning `.gitignore` plus directories literally named
  // `node_modules`/`dist` would itself be excluded by this repository's own
  // real git ignore handling if it were committed as source, since there is
  // no way for git to tell "test data that happens to be a .gitignore" apart
  // from an actual one.
  let scratchRoot: string;

  beforeAll(() => {
    scratchRoot = mkdtempSync(join(tmpdir(), "spectrace-indexer-exclusions-"));
    mkdirSync(join(scratchRoot, "src"), { recursive: true });
    mkdirSync(join(scratchRoot, "node_modules", "some-package"), { recursive: true });
    mkdirSync(join(scratchRoot, "dist"), { recursive: true });
    mkdirSync(join(scratchRoot, "ignored-dir"), { recursive: true });

    writeFileSync(
      join(scratchRoot, "src", "index.ts"),
      "export function add(a: number, b: number): number {\n  return a + b;\n}\n"
    );
    writeFileSync(join(scratchRoot, "src", "vendor.min.js"), "function skip(){return 1}\n");
    writeFileSync(
      join(scratchRoot, "src", "auto-generated.ts"),
      "// @generated by some-tool. Do not edit.\nexport function shouldBeSkipped(): void {}\n"
    );
    writeFileSync(
      join(scratchRoot, "node_modules", "some-package", "index.ts"),
      "export function shouldNeverBeIndexed(): void {}\n"
    );
    writeFileSync(join(scratchRoot, "dist", "generated.js"), "function shouldNeverBeIndexedEither(){return 1}\n");
    writeFileSync(join(scratchRoot, ".gitignore"), "ignored-dir/\n");
    writeFileSync(join(scratchRoot, "ignored-dir", "file.ts"), "export function shouldBeGitignored(): void {}\n");
  });

  afterAll(() => {
    rmSync(scratchRoot, { recursive: true, force: true });
  });

  function indexScratch(): CodeSymbol[] {
    return indexRepository({ repositoryRoot: scratchRoot, repositoryCommit: COMMIT }).symbols;
  }

  it("never indexes node_modules, build output, gitignored, minified, or generated-marked files", () => {
    const symbols = indexScratch();
    const paths = new Set(symbols.map((s) => s.relativePath));

    expect([...paths].some((p) => p.includes("node_modules"))).toBe(false);
    expect([...paths].some((p) => p.includes("dist/"))).toBe(false);
    expect([...paths].some((p) => p.includes("ignored-dir/"))).toBe(false);
    expect(paths.has("src/vendor.min.js")).toBe(false);
    expect(paths.has("src/auto-generated.ts")).toBe(false);
  });

  it("indexes the files that should survive exclusion", () => {
    const symbols = indexScratch();
    const paths = new Set(symbols.map((s) => s.relativePath));
    expect(paths.has("src/index.ts")).toBe(true);
  });

  it("REQ-CORE-011 AC1: adding an exclusion pattern and re-indexing removes the affected symbols", () => {
    const before = indexScratch();
    expect(before.some((s) => s.relativePath === "src/index.ts")).toBe(true);

    const after = indexRepository({
      repositoryRoot: scratchRoot,
      repositoryCommit: COMMIT,
      additionalExcludePatterns: ["src/index.ts"]
    }).symbols;
    expect(after.some((s) => s.relativePath === "src/index.ts")).toBe(false);
    // The stale-proposal half of AC1 is exercised once proposals exist (Phase D).
  });
});

describe("indexRepository — required source units (REQ-CORE-010; prelim spec §8.1)", () => {
  it("extracts a file symbol per surviving source file", () => {
    const symbols = index();
    const fileSymbols = symbols.filter((s) => s.kind === "file");
    expect(fileSymbols.map((s) => s.relativePath).sort()).toEqual([
      "src/index.ts",
      "src/session.ts",
      "src/unused-interface.ts",
      "src/util.ts"
    ]);
  });

  it("extracts a module symbol only for files that export something, including interface-only exports", () => {
    const symbols = index();
    const moduleQualifiedNames = symbols.filter((s) => s.kind === "module").map((s) => s.qualifiedName).sort();
    expect(moduleQualifiedNames).toEqual(["src/index", "src/session", "src/unused-interface", "src/util"]);
  });

  it("extracts top-level function declarations, but not unexported internal helpers' export flag", () => {
    const symbols = index();
    const add = byQualifiedName(symbols, "add", "function")[0]!;
    expect(add.exported).toBe(true);
    expect(add.documentation).toMatch(/Adds two numbers/);
    expect(add.signature).toBe("function add(a: number, b: number): number");

    const helper = byQualifiedName(symbols, "internalHelper", "function")[0]!;
    expect(helper.exported).toBe(false);
  });

  it("extracts an exported const-arrow-function as a function symbol", () => {
    const symbols = index();
    const formatName = byQualifiedName(symbols, "formatName", "function")[0]!;
    expect(formatName.exported).toBe(true);
    expect(formatName.signature).toContain("formatName");
  });

  it("extracts classes and their methods/constructor with class-qualified names", () => {
    const symbols = index();
    const cls = byQualifiedName(symbols, "SessionManager", "class")[0]!;
    expect(cls.exported).toBe(true);
    expect(cls.documentation).toMatch(/Manages session lifecycle/);

    const ctor = byQualifiedName(symbols, "SessionManager.constructor", "constructor")[0]!;
    expect(ctor.signature).toContain("constructor(config: SessionConfig)");

    const method = byQualifiedName(symbols, "SessionManager.expireInactive", "method")[0]!;
    expect(method.documentation).toMatch(/Expires a session/);
  });

  it("extracts get/set accessors as method symbols disambiguated by parameter signature", () => {
    const symbols = index();
    const accessors = symbols.filter((s) => s.qualifiedName === "SessionManager.active" && s.kind === "method");
    expect(accessors).toHaveLength(2);
    expect(new Set(accessors.map((s) => s.symbolId)).size).toBe(2);
    for (const accessor of accessors) {
      expect(accessor.symbolId).toMatch(/^ts:src\/session\.ts#SessionManager\.active:method:[0-9a-f]{8}$/);
    }
  });

  it("includes an interface only when referenced as a parameter or return type of an extracted member (spec §8.1)", () => {
    const symbols = index();
    // Session and SessionConfig are both used as parameter types.
    expect(byQualifiedName(symbols, "Session", "interface")).toHaveLength(1);
    expect(byQualifiedName(symbols, "SessionConfig", "interface")).toHaveLength(1);
    // NeverReferenced is exported but never used as a parameter/return type anywhere.
    expect(byQualifiedName(symbols, "NeverReferenced", "interface")).toHaveLength(0);
  });

  it("includes an interface named in additionalInterfaceNames even if unreferenced", () => {
    const { symbols } = indexRepository({
      repositoryRoot: repoRoot,
      repositoryCommit: COMMIT,
      additionalInterfaceNames: new Set(["NeverReferenced"])
    });
    expect(byQualifiedName(symbols, "NeverReferenced", "interface")).toHaveLength(1);
  });
});

describe("indexRepository — determinism and identity (REQ-CORE-010 AC1/AC2)", () => {
  it("AC1: produces byte-equivalent output across repeated runs", () => {
    const first = index();
    const second = index();
    expect(JSON.stringify(first)).toBe(JSON.stringify(second));
  });

  it("AC2: a symbol's identifier survives edits to its body (declaration-based identity)", () => {
    const scratch = mkdtempSync(join(tmpdir(), "spectrace-indexer-identity-"));
    try {
      const file = join(scratch, "math.ts");
      writeFileSync(file, "export function add(a: number, b: number): number {\n  return a + b;\n}\n");
      const before = indexRepository({ repositoryRoot: scratch, repositoryCommit: COMMIT }).symbols;
      const idBefore = before.find((s) => s.qualifiedName === "add")!.symbolId;

      writeFileSync(
        file,
        "export function add(a: number, b: number): number {\n  const sum = a + b;\n  return sum; // edited body\n}\n"
      );
      const after = indexRepository({ repositoryRoot: scratch, repositoryCommit: COMMIT }).symbols;
      const idAfter = after.find((s) => s.qualifiedName === "add")!.symbolId;

      expect(idAfter).toBe(idBefore);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  });

  it("AC3: indexing the committed example repository completes well inside the 60 s budget", () => {
    // The definitive AC3 measurement runs against the controlled repository
    // on the evaluation baseline machine; this guards against gross regressions.
    const exampleRepo = join(here, "..", "..", "..", "fixtures", "todo-example");
    const startedAt = performance.now();
    const { symbols } = indexRepository({ repositoryRoot: exampleRepo, repositoryCommit: COMMIT });
    const elapsedMs = performance.now() - startedAt;
    expect(symbols.length).toBeGreaterThan(0);
    expect(elapsedMs).toBeLessThan(60_000);
  });

  it("stamps every symbol with the given repository commit", () => {
    const symbols = index();
    expect(symbols.every((s) => s.repositoryCommit === COMMIT)).toBe(true);
  });

  it("gives every symbol a symbolId that resolves to an existing file in the corpus", () => {
    const symbols = index();
    for (const symbol of symbols) {
      expect(symbol.symbolId.startsWith(`ts:${symbol.relativePath}#`)).toBe(true);
    }
  });
});
